return {
	aerial = true,
	beacon = false,
	bufferline = true,
	cmp = true,
	dashboard = true,
	highlighturl = true,
	hop = false,
	indent_blankline = true,
	lightspeed = false,
	["neo-tree"] = true,
	notify = true,
	["nvim-tree"] = false,
	["nvim-web-devicons"] = true,
	rainbow = true,
	symbols_outline = false,
	telescope = true,
	treesitter = true,
	vimwiki = false,
	["which-key"] = true,
}
